---
- name: Read os-family-dependent vars
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Check to see if solr_core_conf_source exists
  stat:
    path: "{{ solr_core_conf_source }}"
  register: result_src

- name: Assert the presence of solr_core_conf_source ({{ solr_core_conf_source }})
  assert:
    that:
      - "result_src.stat.exists and result_src.stat.isdir"
    fail_msg: >-
      The path specified by `solr_core_conf_source` does not exist. Make sure the path is correct, and that the config files have been deployed to that directory.

- name: Check to see if solr_core_conf_dest exists
  stat:
    path: "{{ solr_core_conf_dest }}"
  register: result_dest

- debug:
    var: solr_core_conf_dest
- debug:
    var: result_dest

- name: Assert the presence of solr_core_conf_dest ({{ solr_core_conf_dest }})
  assert:
    that:
      - "result_dest.stat.exists and result_dest.stat.isdir"
    fail_msg:
      - The path specified by `solr_core_conf_dest` does not exist. Has the core `{{ solr_core_name }}` been created?
      - Possible causes for this error include
      - • The core is not listed in the geerlingguy.solr role's list of `solr_cores`
      - • The core creation play did not run
      - • The core name was misspelled either in this play, or in the core creation play
      - • If there are multiple solr services running, the wrong service was specified, or the correct service specification was omitted


- name: Copy the solr schema into the core's conf directory
  become: "{{ solr_core_conf_synchronize_become }}"
  synchronize:
    src: "{{ solr_core_conf_source }}/"
    dest: "{{ solr_core_conf_dest }}/"
    archive: true
    checksum: true
    compress: false
    delete: true
    dirs: true
    group: false
    mode: "{{ solr_core_conf_synchronize_mode }}"
    owner: false
    perms: false
    recursive: true
    times: false
  delegate_to: "{{ solr_core_conf_synchronize_delegate_to }}"
  when: result_src is defined
    and result_src.stat is defined
    and result_src.stat.exists
    and result_dest is defined
    and result_dest.stat is defined
    and result_dest.stat.exists
  notify: arscc restart solr
  register: sync_solr_conf

- name: Reset permissions on solr core config files
  command: >
    /bin/chown -Rv solr:solr "{{ solr_core_conf_dest }}"
  when: sync_solr_conf.changed

- name: Build the cron command string
  set_fact:
    solr_cron_command: >
      {{ arscc_path_to_service_binary }} {{ solr_service_name }} restart > /dev/null
  when: enable_solr_restart == true

- name: Create limitnofile
  template:
    src: templates/limitnofile.j2
    dest: /etc/security/limits.d/{{ solr_service_name }}.limitnofile.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - arscc restart solr

- name: Restart solr
  cron:
    user: "root"
    name: "Restart Solr Service"
    hour: '{{ solr_cron_hours }}'
    minute: "{{ solr_cron_minutes }}"
    job: "{{ solr_cron_command }}"
  when: solr_cron_command != ''
