---
- name: Converge
  hosts: all
  become: true

  vars:
    - solr_service_name: solr
    - solr_home: /var/solr
    - solr_core_name: test
    - solr_core_conf_source: "/var/www/solr_conf/"
    - solr_core_conf_dest: "{{ solr_home }}/data/{{ solr_core_name }}/conf"

  roles:
    - role: ansible-role-solr-core-config
