---
- name: Converge
  hosts: all
  become: true

  vars:

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

  roles:
    - role: ansible-role-solr-core-config
