---
- name: Converge
  hosts: all
  become: true

  vars:
    solr_service_name: solr
    solr_home: /var/solr
    solr_core_name: test
    solr_core_conf_source: "{{ solr_home }}/data/{{ solr_core_name }}/conf"
    solr_core_conf_dest: "{{ solr_home }}/data/{{ solr_core_name }}/conf"
  pre_tasks:

    - name: Create solr conf directory
      file:
        path: /var/solr/data/test/conf
        state: directory


    - name: Install rsync
      package:
        name: rsync
        state: present

  roles:
    - role: ansible-role-solr-core-config
