---
- name: Prepare targets for converge
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

    - name: Update yum
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Ensure ssh client is installed
      package:
        name:
          - openssh-clients
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure rsync exists on the controller
      package:
        name:
          - rsync
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure rsync exists on the controller
      apt:
        pkg:
          - rsync
        state: present
      when: ansible_os_family == 'Ubuntu'

    - name: Create solr conf directory
      file:
        path: /var/solr/data/test/conf
        state: directory

    - name: Create conf folder
      file:
        path: /var/www/solr_conf
        state: directory

    - name: Copy the solr schema into a temp folder
      synchronize:
        src: "conf/7.x/"
        dest: "/var/www/solr_conf/"

