---
- name: Verify role
  hosts: all
  become: yes
  vars:
    solr_core_conf_dest: "/var/solr/data/test/conf"
    solr_config_xml_source: "/var/www/solr_conf/solrconfig.xml"
    solr_core_properties_dest: "/var/solr/data/test/conf/solrconfig.xml"

  tasks:
    - name: Check permissions on solr conf folder
      shell: ls -ld "{{ solr_core_conf_dest }}" | grep 'solr'
      register: solr_permission
    - debug: var=solr_permission.stdout_lines


    - name: Check the properties of source file
      stat:
        path: "{{ solr_config_xml_source }}"
        checksum_algorithm: sha256
      register: source
    - debug: var=source


    - name: Check the properties of destination file
      stat:
        path: "{{ solr_core_properties_dest }}"
        checksum_algorithm: sha256
      register: dest
    - debug: var=dest

    - assert:
        that:
          - source.stat.checksum == dest.stat.checksum
          - source.stat.gr_name == dest.stat.gr_name
          - source.stat.uid == dest.stat.uid

