---
- name: Verify role
  hosts: all
  become: yes
  vars:
    solr_core_conf_dest: "/var/solr/data/test/conf"
    solr_config_xml_source: "{{ playbook_dir }}/conf/7.x/solrconfig.xml"
    solr_core_properties_dest: "/var/solr/data/test/conf/solrconfig.xml"

  tasks:
    - name: Check permissions on solr conf folder
      shell: >
        set -ue -o pipefail;
        ls -ld "{{ solr_core_conf_dest }}" | grep 'solr'
      args:
        executable: /bin/bash
      register: solr_permission

    - name: debug solr_permission.stdout_lines
      debug:
        var: solr_permission.stdout_lines


    - name: Check the properties of local source file
      delegate_to: localhost
      become: false
      stat:
        path: "{{ solr_config_xml_source }}"
        checksum_algorithm: sha256
      register: source

    - name: debug source
      debug:
        var: source

    - name: Query the properties of destination file
      stat:
        path: "{{ solr_core_properties_dest }}"
        checksum_algorithm: sha256
      register: dest
    - debug: var=dest

    - name: Assert core file properties
      assert:
        that:
          - source.stat.checksum == dest.stat.checksum
          - source.stat.gr_name == dest.stat.gr_name
          - source.stat.uid == dest.stat.uid

    - name: Query soft open file limit for solr process
      # The "pgrep java" trick only works because we know we only have one java process.
      shell: >
        set -ue -o pipefail;
        grep 'open files' /proc/$(pgrep java)/limits  | awk '{print $4}'
      args:
        executable: /bin/bash
      register:
        limit_soft_result

    - name: Ensure the soft open file limit is what we want
      assert:
        that:
          - limit_soft_result.stdout == '65000'

    - name: Query hard open file limit for solr process
      # The "pgrep java" trick only works because we know we only have one java process.
      shell: >
        set -ue -o pipefail;
        grep 'open files' /proc/$(pgrep java)/limits  | awk '{print $5}'
      args:
        executable: /bin/bash
      register:
        limit_hard_result

    - name: Ensure hard open file limit is what we want
      assert:
        that:
          - limit_hard_result.stdout == '65000'
